#
# Nitrogen v4.0.0 Configuration File
#

server:
  # Should players be teleported to spawn when they join?
  spawn_on_join: 'false'
  # Should items be dropped when a person dies?
  drop_items_on_death: 'true'
  # Should a person's inventory be cleared when they join the game?
  clear_inventory_on_join: 'false'
  # Should players lose hunger?
  hunger_enabled: 'true'
  # Should weather be enabled?
  weather_enabled: 'true'
  # Should fall damage be enabled?
  fall_damage_enabled: 'true'
  # Is developer mode enabled?
  dev: 'false'
  # Are splash potions enabled?
  splash_potions_enabled: 'true'
  # Are login messages enabled?
  login_messages_enabled: 'true'
commands:
  # Should admin applications be enabled?
  applications_enabled: 'false'
  # What is the link to the admin application template?
  admin_application_template: 'none'
  # What is the link to create a new thread?
  admin_app_new_thread_link: 'none'
  # Should fun comamnds like /ship, /deafen, and /lockup be enabled? (enabled/disabled)
  fun_commands: 'enabled'
players:
  # Who is the owner?
  owner: 'Telesphoreo'
  # Who should be allowed to use some high level commands
  superusers: 'Telesphoreo, OxLemonxO'
social_links:
  GitHub: 'https://www.github.com/FuseMinecraft/Nitrogen'
  Discord: 'https://discord.gg/example'
login-messages:
  Moderator:
    permission: nitrogen.moderator
    message: "&b%player% is a &dModerator"
  Admin:
    permission: nitrogen.admin
    message: "&b%player% is an &4Admin"
  Builder:
    permission: nitrogen.builder
    message: "&b%player% is a Builder"
  Developer:
    permission: nitrogen.developer
    message: "&b%player% is a &5Developer"
  Owner:
    permission: nitrogen.owner
    message: "&b%player% is the &4Owner"
  yashi4554:
    permission: nitrogen.yashi4554
    message: "&b%player% is an &4Admin&b and the &9The Supreme Builder"
