#
# Nitrogen v5.2 Configuration File
#

server:
  # Should players teleport to spawn when they join? (true/false)
  spawn_on_join: false
  # Should items be dropped when a person dies? (true/false)
  drop_items_on_death: true
  # Should a person's inventory be cleared when they join the game? (true/false)
  clear_inventory_on_join: false
  # Should players lose hunger? (true/false)
  hunger_enabled: true
  # Should weather be enabled? (true/false)
  weather_enabled: true
  # Should fall damage be enabled? (true/false)
  fall_damage_enabled: true
  # Is developer mode enabled? (true/false)
  dev: false
  # Are splash potions enabled? (true/false)
  splash_potions_enabled: true
  # Are login messages enabled? (true/false)
  login_messages_enabled: true
commands:
  # Should admin applications be enabled? (true/false)
  applications_enabled: false
  # What is the link to the admin application template?
  admin_application_template: 'none'
  # What is the link to create a new thread?
  admin_app_new_thread_link: 'none'
  # Should fun commands like /ship, /deafen, and /lockup be enabled? (true/false)
  fun_commands: true
players:
  # Who is the owner?
  owner:
    - Jewish_Luigi
  # Who should be allowed to use some high level commands
  superusers:
    - Jewish_Luigi
    - OxLemonxO
social_links:
  GitHub: 'https://www.github.com/FuseMinecraft/Nitrogen'
  Discord: 'https://discord.gg/example'