name: ${project.name}
version: ${project.version}
description: Utility plugin for Minecraft servers
authors: [Telesphoreo, OxLemonxO, Madgeek1450, Prozza, TheMinecraft]
main: me.telesphoreo.Nitrogen
api-version: 1.14
commands:
  adminchat:
    description: Talk privately with other admins
    aliases: o
    permission: nitrogen.adminchat
    usage: /<command> <message>
  admininfo:
    description: Tells a person how to apply for admin
    aliases: [ai, apply]
    usage: /<command>
  clearlag:
    description: Removes server entities
    permission: nitrogen.clearlag
    aliases: [entitywipe, ew, rd]
    usage: /<command> [-s]
  commandspy:
    description: Spy on other players commands
    aliases: cmdspy
    permission: nitrogen.commandspy
    usage: /<command>
  consolesay:
    description: Chat from the console
    aliases: csay
    usage: /<command> <message>
  contributors:
    description: Shows the people who contributed to Nitrogen
    aliases: contributers
    usage: /<command>
  deafen:
    description: Make some noise
    permission: nitrogen.deafen
    usage: /<command>
  developer:
    description: Developer command (Requires superuser)
    aliases: dev
    usage: /<command> <on | off | status>
  expel:
    description: Pushes players away from you
    permission: nitrogen.expel
    usage: /<command>
  fw:
    description: Shoots a firework into the sky
    usage: /<command>
  gcmd:
    description: Makes a player execute a command
    permission: nitrogen.gcmd
    usage: /<command> [player] [command]
  glassmode:
    description: Makes yourself invisible and glow
    permission: nitrogen.glassmode
    usage: /<command> <enable | disable>
  links:
    description: Shows all of the servers links
    usage: /<command>
  lockup:
    description: Block a players Minecraft input
    permission: nitrogen.lockup
    usage: /<command> <all | purge | <<player> on | off>>
  namehistory:
    description: Shows the name history of a player
    aliases: nh
    permission: nitrogen.namehistory
    usage: /<command> <player>
  nitrogen:
    description: Shows information about Nitrogen
    usage: /<command> [reload | debug | help]
  pluginmanage:
    description: Manage plugins
    aliases: [plc, pm]
    permission: nitrogen.pluginmanage
    usage: /<command> <<enable | disable | reload> <pluginname>> | list>
  rename:
    description: Renames the item in your hand
    usage: /<command> <name>
  ship:
    description: Ships a player with another player
    usage: /<command> <player1> <player2>
  terminal:
    description: Send commands from the terminal (Requires superuser)
    usage: /<command>
  toggle:
    description: Toggles configuration options
    usage: /<command>
    permission: nitrogen.toggle
  tprandom:
    description: Teleports a player to a random location
    aliases: tpr
    permission: nitrogen.tprandom
    usage: /<command>
  unloadchunks:
    description: Unloads unused chunks
    aliases: [uc, rc]
    permission: nitrogen.unloadchunks
    usage: /<command> [-s]