name: Fuse
version: 2.0
description: Utility plugin for Minecraft servers
authors: [Telesphoreo, OxLemonxO, Madgeek1450, Prozza, TheMinecraft]
main: com.fusenetworks.fuse.Fuse
commands:
  adminchat:
    description: Talk with other admins
    aliases: o
    permission: fuse.adminchat
    usage: /<command> <message>
  admininfo:
    description: Tells a person how to apply for moderator
    aliases: [ai, apply]
    usage: /<command>
  clearlag:
    description: Removes server entities
    permission: fuse.clearlag
    aliases: [ew, rd]
    usage: /<command> [-s]
  commandspy:
    description: Spy on other players commands
    aliases: cmdspy
    permission: fuse.cmdspy
    usage: /<command>
  consolesay:
    description: Chat from the console
    aliases: csay
    usage: /<command> <message>
  developer:
    description: Developer command (Requires superuser)
    aliases: dev
    usage: /<command> <on | off | status>
  discord:
    description: Gives a link to the Discord server
    usage: /<command>
  expel:
    description: Pushes players away from you
    permission: fuse.expel
    usage: /<command>
  forums:
    description: Gives a link to the forums
    aliases: [forum, fourms, fourm]
    usage: /<command>
  fuse:
    description: Shows information about Fuse
    aliases: [packscore, oxygen, sky, nitrogen, trident]
    usage: /<command> [reload | debug | help | update]
  fw:
    description: Shoots a firework in the sky
    usage: /<command>
  gcmd:
    description: Makes another player do a command
    permission: fuse.gcmd
    usage: /<command> [player] [command]
  glassmode:
    description: Makes yourself invisible and glow
    permission: fuse.glassmode
    usage: /<command> <enable | disable>
  namehistory:
    description: Checks a players name history
    permission: fuse.namehistory
    usage: /<command> <player>
  pluginmanage:
    description: Manage plugins
    aliases: [plc, pm]
    permission: fuse.pluginmanage
    usage: /<command> <<enable | disable | reload> <pluginname>> | list>
  rename:
    description: Rename an item
    usage: /<command> <name>
  ship:
    description: Ships a player with another player
    usage: /<command> <player1> <player2>
  terminal:
    description: Send terminal commands (Requires superuser)
    usage: /<command>
  tprandom:
    description: Teleports to a random place
    aliases: tpr
    permission: fuse.tprandom
    usage: /<command>
  unloadchunks:
    description: Unloads unused chunks
    aliases: [uc, rc]
    permission: fuse.unloadchunks
    usage: /<command> [-s]
  website:
    description: Gives a link to the website
    usage: /<command>