name: Fuse
version: 2.0
description: Utility plugin for Minecraft servers
authors: [Telesphoreo, OxLemonxO, Madgeek1450, Prozza, TheMinecraft]
main: com.fusenetworks.fuse.Fuse
commands:
    player:
      usage: /<command>
      description: Get the location of a player
