name: Fuse
version: 2.0
description: Utility plugin for Minecraft servers
authors: [Telesphoreo, OxLemonxO, Madgeek1450, Prozza, TheMinecraft]
main: com.fusenetworks.fuse.Fuse
commands:
    adminchat:
      usage: /<command> <message>
      description: Talk with other admins
      permission: fuse.adminchat
      aliases: o
    admininfo:
      usage: /<command>
      description: Learn how to apply for moderator
      aliases: ai
    clearlag:
      usage: /<command> [-s]
      description: Clear entities
      aliases: ew
    commandspy:
      usage: /<command>
      description: Spy on other players comamnds
      permission: fuse.commandspy
      aliases: cmdspy
    consolesay:
      usage: /<command> <message>
      description: Talk from the console
      aliases: csay
    contributors:
      usage: /<command>
      description: Shows the contributors to Fuse
      aliases: contributers
    player:
      usage: /<command>
      description: Tells you if your a player or not
      aliases: testcmd
    unloadchunks:
      usage: /<command> [-s]
      description: Clear unused chunks
